version: '3.7'
services:
  database:
    image: 'mysql:8.0'
    volumes:
      - mysql-bdd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sfav2023w51
    ports:
      - '3306:3306'
  pma:
    depends_on:
      - database
    image: phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
  inbucket:
    image: inbucket/inbucket
    ports:
      - "9000:9000"
      - "2500:2500"
      - "1100:1100"

volumes:
  mysql-bdd:
